"""initial schema

Revision ID: 0e1500461b18
Revises: 
Create Date: 2026-09-20 12:27:41.842407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e1500461b18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('farmers',
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('farmer_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('livestock',
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('species', sa.Enum('CATTLE', 'CHICKEN', 'GOAT', 'SHEEP'), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE'), nullable=False),
    sa.Column('breed', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('b_record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['b_record_id'], ['breeding_record.b_record_id'], name='fk_livestock_breeding_event', use_alter=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.farmer_id'], ),
    sa.PrimaryKeyConstraint('animal_id')
    )
    op.create_table('workers',
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.farmer_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('worker_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('breeding_record',
    sa.Column('b_record_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('sire_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('EXPECTANT', 'SUCCESSFUL BIRTH', 'NO BIRTH'), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('num_stillborn', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['livestock.animal_id'], ),
    sa.ForeignKeyConstraint(['sire_id'], ['livestock.animal_id'], ),
    sa.PrimaryKeyConstraint('b_record_id')
    )
    op.create_table('commercial_info',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('BUY', 'SELL'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('other_party', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['livestock.animal_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('health_records',
    sa.Column('h_record_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('treatment', sa.String(length=100), nullable=True),
    sa.Column('dosage', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['livestock.animal_id'], ),
    sa.PrimaryKeyConstraint('h_record_id')
    )
    op.create_table('mortality_records',
    sa.Column('m_record_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('date_of_death', sa.Date(), nullable=False),
    sa.Column('age_at_death', sa.Integer(), nullable=True),
    sa.Column('cause_of_death', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['livestock.animal_id'], ),
    sa.PrimaryKeyConstraint('m_record_id'),
    sa.UniqueConstraint('animal_id')
    )
    op.create_table('production_data',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('item', sa.String(length=100), nullable=False),
    sa.Column('yield', sa.Float(), nullable=False),
    sa.Column('metric', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['livestock.animal_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('weight_records',
    sa.Column('w_record_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['livestock.animal_id'], ),
    sa.PrimaryKeyConstraint('w_record_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weight_records')
    op.drop_table('production_data')
    op.drop_table('mortality_records')
    op.drop_table('health_records')
    op.drop_table('commercial_info')
    op.drop_table('breeding_record')
    op.drop_table('workers')
    op.drop_table('livestock')
    op.drop_table('farmers')
    op.drop_table('users')
    # ### end Alembic commands ###
